Refactor build configs and improve CI/CD checks
This commit makes the build process more robust, simplifies
configurations and reduce the risk of incomplete or erroneous
deployments.

- Centralize output directory definitions by introducing
  `dist-dirs.json`.
- Add `verify-build-artifacts` utility to ensure correct build outputs
  and `print-dist-dir` to determine distribution directory.
- Add steps in CI/CD pipeline to verify build artifacts.
- Migrate Electron Builder config from YAML to CJS for capability to
  read JSON.
- Fix `release-site.yaml` failing due to pointing to wrong distribution
  directory, change it to use `print-dist-dir`.
- Improve `check-desktop-runtime-errors` to verify build artifacts for
  more reliable builds. Ensure tests fail and succeed reliably.
- Update `.gitignore` and configure ESLint to use it to define and
  ignore build artifact directories from one place, remove
  `.eslintignore` that does not add anything after this change.
- Keep `"main"` field in `package.json` as `electron-vite` depends on it
  (alex8088/electron-vite#270).
- Improve documentation

diff --git a/.github/workflows/release.site.yaml b/.github/workflows/release.site.yaml
--- a/.github/workflows/release.site.yaml
+++ b/.github/workflows/release.site.yaml
@@ -95,10 +95,20 @@ jobs:
         run: npm run build
         working-directory: app
       -
+        name: "App: Verify web build artifacts"
+        run: npm run check:verify-build-artifacts -- --web
+        working-directory: app
+      -
         name: "App: Deploy to S3"
+        shell: bash
         run: >-
+          declare web_output_dir
+          if ! web_output_dir=$(cd app && node scripts/print-dist-dir.js --web); then
+            echo 'Error: Could not determine distribution directory.'
+            exit 1
+          fi
           bash "aws/scripts/deploy/deploy-to-s3.sh" \
-            --folder app/dist \
+            --folder "${web_output_dir}" \
             --web-stack-name privacysexy-web-stack --web-stack-s3-name-output-name S3BucketName \
             --storage-class ONEZONE_IA \
             --role-arn ${{secrets.AWS_S3_SITE_DEPLOYMENT_ROLE_ARN}} \
