Bump node environment to 15.x
It updates node version to 15.x to be able to use
`String.prototype.replaceAll()`

diff --git a/.github/workflows/security-checks.yaml b/.github/workflows/security-checks.yaml
--- a/.github/workflows/security-checks.yaml
+++ b/.github/workflows/security-checks.yaml
@@ -18,7 +18,7 @@ jobs:
         name: Setup node
         uses: actions/setup-node@v1
         with:
-          node-version: 14.x
+          node-version: 15.x
       -
         name: NPM audit
-        run: npm audit
+        run: exit "$(npm audit)" # Since node 15.x, it does not fail with error if we don't explicitly exit
